language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install mock
  - pip install requests
  
before_script:
  - npm install karma
  - npm install karma-jasmine
  - npm install karma-coverage
  - npm install karma-phantomjs-launcher

# command to run tests
script:
  - python setup.py test
  - karma start --single-run --browsers PhantomJS samplejsapp/test/karma.conf.js